/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class Crear_cuentas extends javax.swing.JFrame {
      static Clase_principal[] cuenta_cre=new Clase_principal[5];
             mostrar_clientes ms=new mostrar_clientes(); 
  
    public Crear_cuentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cli = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox<>();
        crear = new javax.swing.JButton();
        refre = new javax.swing.JButton();
        lb_indice = new javax.swing.JLabel();
        mostrar_clie = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanel1.setLayout(null);

        cli.setText("cliente");
        jPanel1.add(cli);
        cli.setBounds(240, 190, 35, 16);

        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        jPanel1.add(combo);
        combo.setBounds(100, 260, 300, 22);

        crear.setText("Crear");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });
        jPanel1.add(crear);
        crear.setBounds(220, 360, 72, 22);

        refre.setText("afrefar cliente");
        refre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreActionPerformed(evt);
            }
        });
        jPanel1.add(refre);
        refre.setBounds(200, 220, 110, 22);

        lb_indice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(lb_indice);
        lb_indice.setBounds(230, 300, 60, 30);

        mostrar_clie.setText("Ver cliente");
        mostrar_clie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrar_clieActionPerformed(evt);
            }
        });
        jPanel1.add(mostrar_clie);
        mostrar_clie.setBounds(200, 420, 120, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreActionPerformed
      
        
        Crearclientes cc=new Crearclientes();
        Clase_principal[]dato=cc.client;
       
        combo.removeAllItems();
        
        
            for (int i = 0; i <dato.length; i++) {
            if(dato[i]!=null){
            combo.addItem(dato[i].cui+dato[i].nombre);
            }
                
        }
    }//GEN-LAST:event_refreActionPerformed

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        Clase_principal[] cc=new Clase_principal[5];
        
             int pos=combo.getSelectedIndex();
             

             int ids=1250;
            for (int i = 0; i <cc.length; i++) {
            if (cc[i]!=null){
                for (int j = 0; j <cc[i].cuenta_cre.length; j++) {
                    if (cc[i].cuenta_cre[j]==null){
                    cc[i].cuenta_cre[j]=new cuenta_clie(ids,Integer.parseInt(cc[i].cui),0.0);
                    }
    
                }
            
            }
        }
 
            
    }//GEN-LAST:event_crearActionPerformed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        lb_indice.setText(String.valueOf(combo.getSelectedIndex()));
        
        int cliente_elegido=combo.getSelectedIndex();
        Crearclientes cs=new Crearclientes();
      System.out.println(cs.client[cliente_elegido].cui+cs.client[cliente_elegido].nombre+cs.client[cliente_elegido].apellido);
    }//GEN-LAST:event_comboActionPerformed

    private void mostrar_clieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrar_clieActionPerformed
    mostrar_clientes cambio = new mostrar_clientes();
        cambio.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_mostrar_clieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crear_cuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crear_cuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crear_cuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crear_cuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crear_cuentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cli;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JButton crear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_indice;
    private javax.swing.JButton mostrar_clie;
    private javax.swing.JButton refre;
    // End of variables declaration//GEN-END:variables
}
