


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class mostrar_clientes extends javax.swing.JFrame {
   int datoclil=0;
   /* Crearclientes kl=new Crearclientes();
    Clase_principal[]datocli=kl.client;
    
    Crear_cuentas ms=new Crear_cuentas();
    Clase_principal[]datocue=ms.cuenta_cre;
    
    DefaultTableModel dtm=new  DefaultTableModel();
   DefaultTableModel dtmcli=new  DefaultTableModel();
    
   /*public mostrar_clientes() 
   {
       initComponents();
         String[] titul= new String[]{"CUI","Nombre","Apelido"};
         dtm.setColumnIdentifiers(titul);
         tabla_p.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_p = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cui_b = new javax.swing.JTextField();
        agregar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla_c = new javax.swing.JTable();
        refrescar = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(600, 300));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel1.setLayout(null);

        tabla_p.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla_p);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 10, 375, 150);

        jLabel1.setText("cui");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 180, 80, 16);
        jPanel1.add(cui_b);
        cui_b.setBounds(20, 200, 110, 22);

        agregar.setText("Buscar cuentas Asosiadas");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        jPanel1.add(agregar);
        agregar.setBounds(250, 210, 210, 30);

        tabla_c.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane3.setViewportView(tabla_c);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(40, 250, 220, 200);

        refrescar.setText("refrescar");
        refrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refrescarActionPerformed(evt);
            }
        });
        jPanel1.add(refrescar);
        refrescar.setBounds(420, 90, 75, 22);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 510, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
     String[] titul2= new String[]{"cuenta"};
     
        // dtmcli.setColumnIdentifiers(titul2);
         //tabla_c.setModel(dtmcli);
        // String cuidd=cui_b.getText();
        // dtmcli.addRow(new Object[]
        {
            //datocue[i].cuenta_cre=cui_b.getText()
              
               } 
         
    }//GEN-LAST:event_agregarActionPerformed

    private void refrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refrescarActionPerformed
        for (int i = 0; i <0; i++) {
         //   if (datocli[i]!=null){
           // datocli[i]
          break;
            }
                
            
        }
        
      // String Matriz=new String(datocli.length[3]);
       //for (int i = 0; i < 10; i++) 
    {
            
        
           
        
    }//GEN-LAST:event_refrescarActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JTextField cui_b;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton refrescar;
    private javax.swing.JTable tabla_c;
    private javax.swing.JTable tabla_p;
    // End of variables declaration//GEN-END:variables
}
